#!/usr/bin/env python
"""Talking-animal MOVIE via Veo 3 (Kie.ai) — the REAL thing.

All the animals together in ONE cinematic scene, actually talking to each other, with native
audio (dialogue + ambient) generated by Veo 3. Each ~8s shot is generated and the shots are
stitched into a short reel. This is the "wait, is this filmed?" tier.

  python make_animal_movie.py --test          # ONE 8s shot (~$1.20 on veo3_fast) to judge quality
  python make_animal_movie.py                 # full story (4 shots, ~$5 on veo3_fast)
  python make_animal_movie.py --model veo3     # top quality (Standard, pricier ~$3.20/shot)

Needs KIE_API_KEY in .env (sign up + add credit at https://kie.ai).
"""
import argparse
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

# One consistent cinematic scene described every shot so the trio + setting stay coherent.
STYLE = ("Cinematic photorealistic wildlife film, shot on ARRI, shallow depth of field, soft "
         "golden-hour light through the jungle canopy, gentle film grain, natural ambient jungle "
         "sounds. ")
SCENE = ("A majestic male lion with a full mane, a Bengal tiger, and a small fluffy brown rabbit "
         "sit close together in a lush green jungle clearing, like old friends. ")

SHOTS = [
    STYLE + SCENE + 'The lion leans in and rumbles in a deep voice: "Explain something to me about the humans."',
    STYLE + SCENE + 'The tiger smirks and says smoothly: "Every morning they wake and stare at a small glowing rectangle. Before water. Before anything."',
    STYLE + SCENE + 'The little rabbit\'s eyes go wide and it squeaks nervously, paws trembling: "And sometimes they talk to it... and it talks back!"',
    STYLE + SCENE + 'The lion shakes his mane and says gravely: "We rule by strength. They are ruled by a rectangle." The three animals share a long, knowing look.',
]


def _ff():
    import imageio_ffmpeg
    return imageio_ffmpeg.get_ffmpeg_exe()


def stitch(clips, out):
    ff = _ff()
    inputs = []
    for c in clips:
        inputs += ["-i", c]
    n = len(clips)
    fc = "".join(f"[{i}:v][{i}:a]" for i in range(n)) + f"concat=n={n}:v=1:a=1[v][a]"
    subprocess.run([ff, "-y", *inputs, "-filter_complex", fc, "-map", "[v]", "-map", "[a]",
                    "-c:v", "libx264", "-c:a", "aac", "-pix_fmt", "yuv420p", out], capture_output=True)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--test", action="store_true", help="generate only the first shot")
    ap.add_argument("--model", default="veo3_lite", choices=["veo3_lite", "veo3_fast", "veo3"])
    ap.add_argument("--resolution", default="720p", choices=["720p", "1080p"])
    a = ap.parse_args()

    from modules.veo_kie import generate_veo, check_key, estimate_cost
    if not check_key():
        print("KIE_API_KEY not set.\n"
              "  1. Sign up at https://kie.ai\n"
              "  2. Add a few dollars of credit\n"
              "  3. Copy your API key -> add to .env as  KIE_API_KEY=xxxxx\n"
              "  4. Re-run:  python make_animal_movie.py --test", flush=True)
        return

    shots = SHOTS[:1] if a.test else SHOTS
    stamp = time.strftime("%Y%m%d_%H%M%S")
    out = ROOT / "output" / f"animal_movie_{stamp}"
    out.mkdir(parents=True, exist_ok=True)
    est = sum(estimate_cost(a.model, 8) for _ in shots)
    print(f"=== ANIMAL MOVIE (Veo 3 / Kie.ai) — {len(shots)} shot(s), est ~${est:.2f} ===", flush=True)

    clips = []
    for i, prompt in enumerate(shots):
        clip = out / f"shot_{i}.mp4"
        try:
            generate_veo(prompt, str(clip), model=a.model, aspect="9:16",
                         resolution=a.resolution, duration=8)
            clips.append(str(clip))
        except Exception as e:
            print(f"shot {i} FAILED: {e}", flush=True)
    if not clips:
        print("No clips generated.", flush=True)
        return

    final = out / "movie.mp4"
    if len(clips) == 1:
        shutil.copy(clips[0], final)
    else:
        stitch(clips, str(final))
    print(f"MOVIE -> {final}", flush=True)


if __name__ == "__main__":
    main()
