"""
Lip sync for a character that has no mouth rig.

Inspecting the Mixamo model showed the problem plainly: no jaw bone (the only
'tongue' bones belong to the shoes) and no shape keys on any mesh. The mouth
is a static 49-vertex object. So the visemes do not exist and have to be
built, which - because it is only 49 vertices - is a job for a script rather
than a modeller.

Three shape keys are generated by moving those vertices directly:

    OPEN   lower half drops and the whole mouth scales down slightly in width
           - a jaw opening, not a hole appearing
    WIDE   scales across X, for EE and I sounds
    ROUND  scales in on X and up on Z, for OO and OH

Then the audio drives them. Amplitude alone gives a flapping mouth that reads
as a puppet, so this uses the WORD timings we already extract with whisper for
captions: each word gets a shape chosen from its vowels, and the amplitude
inside that word drives how far the shape opens. Between words the mouth
closes. That is what makes speech read as speech rather than as chewing.

    from blender.lipsync import build_visemes, drive_from_words
"""
import math

import bpy

# Vowel -> viseme. Crude by design: at reel size the difference between a
# perfect phoneme set and three well-timed shapes is invisible, while the
# difference between three well-timed shapes and none is the whole effect.
VOWEL_SHAPE = {
    "a": "open", "e": "wide", "i": "wide", "o": "round", "u": "round",
    "y": "wide",
}


def find_mouth(meshes):
    """The mouth mesh. Named h_Geo in this model, so match on material too."""
    for m in meshes:
        n = m.name.lower()
        mats = " ".join(x.name.lower() for x in m.data.materials if x)
        if "mouth" in n or "mouth" in mats or n == "h_geo":
            return m
    return None


def build_visemes(mouth):
    """Generate open/wide/round shape keys by moving vertices directly."""
    if not mouth or mouth.type != "MESH":
        return None
    me = mouth.data
    if not me.shape_keys:
        mouth.shape_key_add(name="Basis", from_mix=False)

    zs = [v.co.z for v in me.vertices]
    lo, hi = min(zs), max(zs)
    span = max(1e-6, hi - lo)
    mid = (lo + hi) / 2

    def add(name, fn):
        kb = mouth.shape_key_add(name=name, from_mix=False)
        for i, v in enumerate(me.vertices):
            kb.data[i].co = fn(v.co.copy(), (v.co.z - lo) / span)
        return kb

    # OPEN: the lower half travels down, the upper half barely moves — a jaw,
    # not a uniform stretch. Weighted by height so the hinge is at the top.
    add("open", lambda co, t: co + type(co)(
        (0.0, 0.0, -(1.0 - t) ** 1.5 * span * 1.35)))
    # WIDE: spread across X, slight flatten in Z
    add("wide", lambda co, t: type(co)((co.x * 1.30, co.y, mid + (co.z - mid) * 0.78)))
    # ROUND: pull in across X, open a little in Z
    add("round", lambda co, t: type(co)((co.x * 0.62, co.y, mid + (co.z - mid) * 1.22)))

    for kb in me.shape_keys.key_blocks:
        kb.slider_min = 0.0
        kb.slider_max = 1.0
        if kb.name != "Basis":
            kb.value = 0.0
    print(f"[LipSync] built visemes on '{mouth.name}' "
          f"({len(me.vertices)} verts)")
    return me.shape_keys


def _shape_for(word):
    """Pick a viseme from the vowels in a word. First vowel wins."""
    for ch in word.lower():
        if ch in VOWEL_SHAPE:
            return VOWEL_SHAPE[ch]
    return "open"


def drive_from_words(mouth, words, fps=30, lead=0.0, gain=1.0):
    """Key the visemes from whisper word timings.

    words: [{"text","start","end"}] — exactly what caption sync already
    produces, so speech drives the mouth from the same source that drives the
    subtitles and the two can never disagree.
    """
    keys = mouth.data.shape_keys
    if not keys:
        return 0
    kb = {k.name: k for k in keys.key_blocks}

    def key_all(frame, active=None, value=0.0):
        for name in ("open", "wide", "round"):
            if name not in kb:
                continue
            kb[name].value = value if name == active else 0.0
            kb[name].keyframe_insert("value", frame=frame)

    n = 0
    for w in words:
        text = (w.get("text") or "").strip()
        if not text:
            continue
        s = (float(w.get("start", 0)) + lead) * fps
        e = (float(w.get("end", 0)) + lead) * fps
        if e <= s:
            e = s + 2
        shape = _shape_for(text)
        # longer words open wider - a rough stand-in for stress
        amp = min(1.0, 0.45 + min(len(text), 8) / 14.0) * gain

        key_all(max(1, int(s - 1)), None, 0.0)          # closed before
        key_all(int(s + (e - s) * 0.35), shape, amp)    # open through
        key_all(int(e), shape, amp * 0.35)              # trailing off
        key_all(int(e + 1), None, 0.0)                  # closed after
        n += 1

    # ease every viseme curve — linear mouth shapes snap and read robotic
    ad = keys.animation_data
    if ad and ad.action:
        for fc in ad.action.fcurves:
            for p in fc.keyframe_points:
                p.interpolation = "BEZIER"
                p.easing = "EASE_IN_OUT"
    print(f"[LipSync] keyed {n} words")
    return n


def words_from_srt(path):
    """Read whisper's SRT into [{'text','start','end'}]."""
    import re
    out = []
    txt = open(path, encoding="utf-8", errors="ignore").read()
    blocks = re.split(r"\n\s*\n", txt)
    for b in blocks:
        m = re.search(r"(\d{2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*"
                      r"(\d{2}):(\d{2}):(\d{2})[,.](\d{3})", b)
        if not m:
            continue
        g = [int(x) for x in m.groups()]
        s = g[0] * 3600 + g[1] * 60 + g[2] + g[3] / 1000
        e = g[4] * 3600 + g[5] * 60 + g[6] + g[7] / 1000
        line = " ".join(b.split("\n")[2:]).strip()
        if not line:
            continue
        # spread the cue's words evenly inside it
        ws = line.split()
        step = (e - s) / max(1, len(ws))
        for i, w in enumerate(ws):
            out.append({"text": w, "start": s + i * step,
                        "end": s + (i + 1) * step})
    return out
